version: '2'

services:
  db:
    image: postgres
    container_name: db
    hostname: db
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/static
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web