FROM python:3
RUN apt-get update && apt-get install -y postgresql postgresql-contrib
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/

ADD docker-entrypoint.test.sh /
RUN chmod +x /docker-entrypoint.test.sh

ENTRYPOINT ["/docker-entrypoint.test.sh"]