# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.TextField(default=''),
        ),
    ]
